services:
    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
    redis:
        image: redis:7-alpine
        # No ports are exposed to the outside world in production.
        # The 'web' and 'worker' services can still access it via the internal Docker network.

    web:
        build: .
        image: ${DOCKERHUB_USERNAME}/bibliotype:${IMAGE_TAG:-latest}
        command: ["poetry", "run", "gunicorn", "bibliotype.wsgi:application", "--bind", "0.0.0.0:8000"]
        volumes:
            - ./staticfiles:/app/staticfiles
        ports:
            - "127.0.0.1:8000:8000"
        environment:
            - DJANGO_ENV=production
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - SECRET_KEY=${SECRET_KEY}
            - POSTHOG_API_KEY=${POSTHOG_API_KEY}
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started

    worker:
        build: .
        image: ${DOCKERHUB_USERNAME}/bibliotype:${IMAGE_TAG:-latest}
        command: sh -c "poetry run celery -A bibliotype worker -l info"
        environment:
            - DJANGO_ENV=production
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - SECRET_KEY=${SECRET_KEY}
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started

volumes:
    postgres_data:
