# Generated by Django 5.2.5 on 2025-08-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('lookup_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('mainstream_score', models.IntegerField(default=0)),
            ],
        ),
    ]
