# Generated by Django 5.2.5 on 2025-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_popularbook_average_rating_popularbook_awards_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_dna_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
