# Generated by Django 5.2.5 on 2025-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250906_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='normalized_name',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
    ]
