# Generated by Django 5.2.5 on 2025-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_normalized_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='normalized_title',
            field=models.CharField(db_index=True, editable=False, max_length=255),
        ),
    ]
