# Generated by Django 5.2.5 on 2025-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_book_awards_won_remove_book_canon_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='mainstream_last_checked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
