# Generated by Django 5.2.5 on 2025-10-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_publisher_mainstream_last_checked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('normalized_title', 'author')},
        ),
    ]
