# Generated by Django 5.2.5 on 2025-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_anonymoususersession_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususersession',
            name='book_ratings',
            field=models.JSONField(default=dict),
        ),
    ]
