# Generated by Django 5.2.5 on 2026-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_aggregateanalytics_avg_books_per_year_dist"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommendations_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
