# Generated by Django 5.2.5 on 2026-03-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_recommendations_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
