# Generated by Django 5.2.5 on 2026-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_last_checked',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
