# Generated by Django 5.2.5 on 2026-06-01 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_book_google_books_last_checked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(condition=models.Q(('dna_data__isnull', False)), fields=['visible_in_recommendations', 'is_public'], name='userprofile_recs_partial_idx'),
        ),
    ]
