# Generated by Django 5.2.5 on 2026-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_create_uniqueness_badge_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
