# dna_constants.py

"""
This file stores the constant data used by the Reading DNA generator.
This is the final, comprehensive version incorporating extensive user feedback.
"""


READER_TYPE_DESCRIPTIONS = {
    "Fantasy Fanatic": [
        "You have a deep love for worlds of magic, myth, and epic quests. Your reading history is filled with fantasy and science fiction.",
        "Your library is a gateway to other realms. You consistently choose books in the fantasy and sci-fi genres.",
        "From dragons to distant galaxies, your reading habits show a clear preference for the imaginative and the speculative.",
    ],
    "Novella Navigator": [
        "You're a master of the short-form narrative, frequently choosing books under 200 pages. You appreciate a story that gets straight to the point.",
        "Your reading data shows a strong preference for shorter books. You enjoy concise, impactful stories that can be read in a single sitting.",
        "You've read a significant number of novellas and shorter works, making you an expert in the art of brevity.",
    ],
    "Small Press Supporter": [
        "You champion the underdogs of the publishing world. A significant portion of your reading comes from independent and small presses.",
        "Your library is filled with hidden gems from outside the major publishing houses. You have a keen eye for unique, independent voices.",
        "By frequently reading books from small presses, you actively support a more diverse literary landscape.",
    ],
    "Tome Tussler": [
        "You aren't afraid of commitment. Your reading history is filled with massive books over 500 pages long.",
        "You love to get lost in sprawling epics and complex narratives, as shown by the number of lengthy tomes you've conquered.",
        "Your results show a clear pattern of tackling the biggest books on the shelf. You're a true heavyweight reader.",
    ],
    "Classic Collector": [
        "You have a great appreciation for the classics. A notable part of your reading list was published before 1970.",
        "Your reading habits show a journey through literary history, with a strong focus on timeless, classic works.",
        "You frequently read books that have stood the test of time, building a library of foundational literary classics.",
    ],
    "Versatile Valedictorian": [
        "Your reading tastes are incredibly diverse. You've explored a wide array of genres, from fiction to non-fiction and everything in between.",
        "You are a true literary explorer. Your results show you've read from more than ten distinct canonical genres.",
        "Your library is a testament to your curiosity, spanning a broad and impressive range of different literary categories.",
    ],
    "Non-Fiction Ninja": [
        "You read to learn and understand the world. Your library is heavily weighted towards non-fiction titles.",
        "From history to science to biography, your reading habits show a strong desire for facts, insights, and real-world knowledge.",
    ],
    "Social Savant": [
        "You are fascinated by the dynamics of society. Your reading list is rich with books on sociology, politics, and current events.",
        "Your library reflects a deep engagement with social structures and human behavior, focusing on the social sciences.",
    ],
    "Modern Maverick": [
        "You have your finger on the pulse of modern literature. You consistently read new releases and books published in the last few years.",
        "Your bookshelf is a snapshot of the current literary moment, showing a strong preference for contemporary authors and recent publications.",
    ],
    "Philosophical Philomath": [
        "You enjoy pondering the big questions. Your reading history shows a recurring interest in philosophical works.",
        "Your library is a space for deep thought, filled with books that explore ethics, existence, and the nature of reality.",
    ],
    "Eclectic Reader": [
        "Your reading habits are balanced and wide-ranging, with no single trait dominating the others. You are a true eclectic reader!",
    ],
}


MAJOR_PUBLISHERS = {
    "penguin",
    "random house",
    "harpercollins",
    "simon & schuster",
    "hachette",
    "macmillan",
    "knopf",
    "doubleday",
    "viking",
    "vintage",
    "scribner",
    "atriabooks",
    "little, brown",
    "bloomsbury",
    "farrar, straus & giroux",
    "bantam",
    "scholastic",
    "putnam",
    "dutton",
    "hodder",
    "collins",
    "oxford university press",
    "routledge",
    "prentice hall",
    "grove press",
    "virago",
    "gollancz",
    "harper",
    "harcourt",
    "faber",
    "dover",
    "tantor",
    "signet",
    "Atria Books",
    "Ballantine Books",
    "Orion Publishing Group",
    "Berkley",
    "Hogarth",
    "Simon and Schuster",
    "Picador",
    "Anchor Canada",
    "Harvill Secker",
    "Farrar, Straus and Giroux",
    "Pearson Education",
}

GENRE_ALIASES = {
    # --- FICTION ---
    "fantasy": {
        "fantasy fiction",
        "epic fantasy",
        "high fantasy",
        "wizards",
        "magic",
        "urban fantasy",
        "magical realism",
        "dragons",
        "discworld (imaginary place)",
        "shapeshifting",
        "english fantasy fiction",
        "american fantasy fiction",
        "fiction, fantasy, epic",
        "mundodisco (lugar imaginario)",
        "novela fantástica",
        "wizards, fiction",
        "magic, fiction",
        "disque-monde (lieu imaginaire)",
        "discworld",
        "giants",
        "knights",
        "quests",
        "fiction, fantasy, general",
        "knights and knighthood",
        "fantastique",
        "quests (expeditions)",
        "discworld (imaginary place",  # Typo fix
    },
    "science fiction": {
        "sci-fi",
        "speculative fiction",
        "dystopian fiction",
        "cyberpunk",
        "space opera",
        "time travel",
        "science fiction, american",
        "utopias",
        "the future",
        "artificial intelligence",
        "totalitarianism",
        "hainish cycle",
        "dune (imaginary place)",
        "science-fiction",
        "fiction, dystopian",
        "dystopias",
        "totalitarianism -- fiction",
        "robots",
    },
    "thriller": {
        "thriller",
        "mystery fiction",
        "crime fiction",
        "suspense fiction",
        "assassins",
        "detective and mystery stories",
        "thrillers (fiction)",
        "spy stories",
        "crime",
        "mystery",
        "murder",
        "murderers",
        "fiction, crime",
        "theft",
        "assassination",
        "fiction, thrillers",
        "detectives",
        "criminal investigation",
        "revenge",
        "crime, fiction",
        "prisons / fiction",
        "brigands and robbers",
        "fiction, thrillers, general",
        "investigation",
        "malicious accusation",
    },
    "horror": {
        "horror fiction",
        "ghost stories",
        "supernatural fiction",
        "gothic fiction",
        "fiction, gothic",
        "supernatural",
        "southern gothic",
        "monsters",
        "horror stories",
        "horror tales",
        "fiction, horror",
        "hell",
        "histoires de fantômes",
        "novela de terror",
    },
    "historical fiction": {
        "historical fiction",
        "roman historique",
        "world war, 1914-18",
        "world war, 1939-45",
        "trojan war",
        "fiction, historical, general",
        "fiction / historical",
        "rome, fiction",
        "war stories",
        "world war i",
        "world war ii",
        "fiction, historical",
        "spain, fiction",
        "greece, fiction",
        "france in fiction",
        "world war, 1914-1918",
        "world war, 1939-1945",
        "princes, fiction",
    },
    "romance": {
        "romance fiction",
        "love stories",
        "contemporary romance",
        "love",
        "love—fiction",
        "love stories, english",
        "fiction, romance, contemporary",
        "courtship",
        "first loves",
        "fiction, romance, general",
        "gay love",
        "english love stories",
    },
    "humorous fiction": {
        "humorous stories",
        "humor",
        "satire",
        "political satire",
        "fiction, satire",
        "humor.",
        "fiction, humorous",
    },
    "young adult": {
        "young adult fiction",
        "juvenile literature",
        "ya",
        "juvenile",
        "teenage fiction",
        "high school students",
        "coming of age",
        "adolescence",
        "runaway teenagers",
        "teenage boys",
        "youth, fiction",
    },
    "children's literature": {
        "children's stories",
        "picture books",
        "boys",
        "children",
        "children's plays",
        "children's plays, english",
    },
    "classics": {
        "classic",
        "classical literature",
        "fiction classics",
        "classic fiction",
        "classic literature",
    },
    "literary fiction": {
        "bildungsroman",
        "bildungsromans",
        "diary novels",
        "epistolary fiction",
        "contemporary",
        "contemporary fiction",
        "modern fiction",
        "fiction, family life",
        "families",
        "fiction / literary",
        "fiction, women",
        "women's fiction",
        "man-woman relationships, fiction",
        "female friendship",
        "friendship, fiction",
        "slice-of-life",
        "family",
        "fiction / sagas",
        "domestic fiction",
        "political fiction",
        "african-american fiction",
        "cultural heritage",
        "fiction, cultural heritage",
        "blacks, fiction",
        "mate selection, fiction",
        "family life, fiction",
        "american fiction",
        "american sea stories",
        "artists, fiction",
        "sagas",
        "campus",
        "college stories",
        "fiction, gay",
        "diaries, fiction",
    },
    "mythology & folklore": {
        "mythology",
        "retellings",
        "gods",
        "folklore",
        "literature: folklore/mythology",
        "fiction / folklore",
        "achilles (mythological character)",
        "achilles (greek mythology)",
        "iphigenia (greek mythology)",
        "thetis",
    },
    "short stories": {"short stories", "english short stories", "short story"},
    "comics & graphic novels": {"cartoons and comics"},
    "holiday fiction": {"christmas stories"},
    "fairy tales & fables": {"fairy tales", "fables"},
    # --- NON-FICTION ---
    "non-fiction": {"nonfiction", "essays", "journalism", "creative nonfiction", "doctrines"},
    "biography": {
        "biography",
        "autobiography",
        "memoir",
        "biographies",
        "memoirs",
        "diaries",
        "fiction, biographical",
        "biography & autobiography",
        "authors, biography",
        "cancer, patients, biography",
        "terminally ill, biography",
        "fiction / biographical",
    },
    "history": {
        "history",
        "world history",
        "ancient history",
        "military history",
        "historia",
        "explosives",
        "munitions",
    },
    "psychology": {
        "mental health",
        "psychology",
        "psychological fiction",
        "evolutionary psychology",
        "fiction, psychological",
        "genetic psychology",
        "behavior evolution",
        "american psychological fiction",
        "mental illness",
        "neuropsychology",
        "cognitive neuroscience",
        "fiction / psychological",
        "recollection (psychology)",
        "aversion therapy",
        "behavior",
        "psychological aspects",
        "degeneration",
        "multiple personality",
    },
    "philosophy": {
        "philosophy",
        "ethics",
        "metaphysics",
        "stoicism",
        "existentialism",
        "good and evil",
        "ancient philosophy",
        "philosophy, ancient",
        "philosophy, christian",
        "fate and fatalism",
        "existentialism in literature",
        "aristotle",
        "appearance (philosophy)",
        "filosofia antiga",
        "filosofia grega",
    },
    "social science": {
        "sociology",
        "politics",
        "social history",
        "anthropology",
        "current events",
        "fiction, political",
        "political science",
        "economics",
        "feminism",
        "feminist theory",
        "feminist ethics",
        "social control",
        "popular culture",
        "race relations",
        "african american studies",
        "social classes, fiction",
        "ethnic studies",
        "pornography, social aspects",
        "racial segregation",
        "women, social conditions",
        "equality",
        "city planning",
        "consumption",
        "feminism and literature",
        "feminist fiction, english",
        "sex role",
    },
    "nature": {
        "natural history",
        "environment",
        "animals",
        "outdoors",
        "nature writing",
        "biology",
        "country life",
        "farm life",
        "dogs, fiction",
        "animals, fiction",
        "zoologists",
        "resource conservation",
        "human-animal relationships",
        "human-animal communication",
        "fishing stories",
        "horses",
        "cats, fiction",
        "rabbits",
    },
    "self-help": {
        "self-help",
        "personal development",
        "self-improvement",
        "productivity",
        "business",
        "conduct of life",
        "self-actualization (psychology)",
        "maturity",
    },
    "science": {
        "science",
        "popular science",
        "physics",
        "astronomy",
        "biological evolution",
        "cosmology",
        "astrophysics",
        "brain",
        "neurology",
        "hallucinogenic drugs",
    },
    "travel": {
        "travel writing",
        "travelogue",
        "voyages and travels",
        "description and travel",
        "imaginary voyages",
        "explorers",
        "discovery and exploration",
        "globetrotter",
    },
    "art & music": {
        "art",
        "art appreciation",
        "visual perception",
        "music",
        "photograph collections",
        "musicians",
        "women rock musicians",
        "portraits",
        "technique",
        "beethoven's fifth symphony",
        "trees in art",
    },
    "food & cooking": {
        "cooking",
        "food",
        "nutrition",
        "eating",
        "cooking & food",
        "cooking methods",
        "food habits",
        "tea",
        "japanese tea ceremony",
        "chadō",
    },
    "plays & drama": {
        "drama",
        "plays / drama",
        "play",
        "plays",
        "english drama",
        "motion picture plays",
        "animal drama",
        "performing arts",
        "french drama",
    },
    "religion & spirituality": {"bible", "christianity", "catholic church"},
}

EXCLUDED_GENRES = {
    # --- LIBRARY OF CONGRESS / DEWEY DECIMAL ---
    "813/.54",
    "823/.6",
    "pr5841.w8 m37 2007",
    "185",
    # --- AWARDS / METADATA ---
    "award:hugo_award=1966",
    "award:hugo_award=novel",
    "award:man_booker_prize=1997",
    "award:nebula_award=novel",
    "hugo award winner",
    "reading level-grade 7",
    "facsimiles",
    "new york times bestseller",
    "protected DAISY",
    "textual criticism",
    "reference",
    "open_syllabus_project",
    "bibliography",
    "catalogs",
    "congresses",
    "promptbooks",
    "special collections",
    "gift books",
    "in library",
    "overdrive",
    "large type books",
    "appreciation",
    "literary criticism",
    "twentieth century",
    # --- LANGUAGES / TRANSLATIONS / NATIONALITIES (NOT GENRES) ---
    "translations into english",
    "french literature",
    "american literature",
    "english fiction",
    "french fiction",
    "fiction in spanish",
    "french language materials",
    "spanish language",
    "english language",
    "language and languages",
    "translations into irish",
    "translations into italian",
    "translations into russian",
    "american authors",
    "english authors",
    "french language",
    "french language books",
    "amerikanisches englisch",
    "ameriška književnost",
    "družbene razmere",
    "dénonciation calomnieuse",
    "medosebni odnosi",
    "morale ancienne",
    "ouvrages avant 1800",
    "rappel (psychologie)",
    "sociale evolutie",
    "v leposlovju",
    "verhaltensforschung",
    # --- SIMPLE / BROAD EXCLUSIONS ---
    "fiction",
    "literature",
    "ficción",
    "fiction, general",
    "romans, nouvelles",
    "english literature",
    "juvenile fiction",
    "children's fiction",
    "general",
    "fiction / general",
    "fictional works",
    "literary",
    "british fiction",
    "fiction - general",
    "academic",
    "crap",
    # --- THEMES / SUBJECTS / CHARACTERS (WHAT A BOOK IS ABOUT, NOT WHAT IT IS) ---
    "abandoned children",
    "adoptees, fiction",
    "african american women",
    "african-americans",
    "alienation in teenagers",
    "alternative family",
    "american poets",
    "ancianos",
    "antoine (marcus antonius)",
    "asperger's syndrome",
    "authorship",
    "autism",
    "black people",
    "boarding schools",
    "books and reading",
    "bulls",
    "businesswomen",
    "campesinos",
    "cancer, fiction",
    "cancer—fiction",
    "catch-22 (heller, joseph)",
    "cats",
    "cemeteries",
    "chelsea hotel",
    "child rearing",
    "classicists",
    "college students",
    "college teachers",
    "contemporary women",
    "country homes",
    "cousins",
    "cousins, fiction",
    "curiosities and wonders",
    "dalit",
    "dancers",
    "dating & sex",
    "death",
    "death, grief, bereavement",
    "discoveries in geography",
    "diseases",
    "dogs",
    "dwellings",
    "economic conditions",
    "ehemann",
    "elderly",
    "emperors",
    "english life",
    "english teachers",
    "etiquette",
    "expedition",
    "families",
    "family life",
    "family relations",
    "family relationships",
    "fathers and daughters",
    "female friendship",
    "feminists",
    "femmes",
    "femmes écrivains",
    "fighting bull",
    "fishers",
    "frankenstein (fictitious character)",
    "fraternal twins",
    "friendship",
    "fugitives from justice",
    "gang rape",
    "gond (indic people)",
    "greeks",
    "grief",
    "guardian and ward",
    "guards troops",
    "guilt",
    "health",
    "heart",
    "high school seniors",
    "hispanic americans, fiction",
    "hombres",
    "homme",
    "hp lovecraft",
    "human beings",
    "husband and wife",
    "illegal alien children",
    "immigrant children",
    "immigrants",
    "interpersonal relations",
    "interpersonal relations, fiction",
    "japan",
    "japanese",
    "labor trilogy",
    "labyrinths",
    "life change events",
    "livres et lecture",
    "love",
    "male friendship",
    "man",
    "man-woman relationships",
    "manners",
    "marital conflict",
    "marriage",
    "marriage, fiction",
    "married people",
    "married people, fiction",
    "married women",
    "mate selection",
    "medication abuse",
    "memory",
    "men",
    "mentally ill women",
    "middle-aged women",
    "missing persons",
    "mistresses",
    "mob mentality",
    "mortality",
    "mothers",
    "mothers and daughters",
    "motion picture industry",
    "moški in ženske",
    "mujeres",
    "musicians",
    "musicians, fiction",
    "médicos",
    "neighbors",
    "neurosurgeons",
    "nigerians",
    "nobility in fiction",
    "nursing homes",
    "older people",
    "opioid abuse",
    "orphans",
    "parental influences",
    "patients",
    "peasants",
    "photographers",
    "photographers, fiction",
    "physicians",
    "physicians in fiction",
    "physicians, fiction",
    "planned communities",
    "poor families",
    "poor families, fiction",
    "pornography",
    "poverty",
    "poverty -- fiction",
    "preparatory school students",
    "preparatory schools",
    "princes",
    "prisons",
    "private schools",
    "psychiatric hospitals",
    "psychotherapy patients",
    "pyramids",
    "pyramids -- fiction.",
    "quacks and quackery",
    "race",
    "readers",
    "rebellion",
    "refugees",
    "reincarnation",
    "revenge",
    "rich people",
    "riot grrrl movement",
    "rock musicians",
    "sailors",
    "savants (savant syndrome)",
    "schools",
    "scientists",
    "scientists, fiction",
    "self-destructive behavior",
    "self-experimentation in medicine",
    "sex",
    "sexual minority culture",
    "shame",
    "single-parent families",
    "sisters",
    "smith, patti, 1946-",
    "social aspects",
    "social conditions",
    "social isolation",
    "social themes",
    "soldiers",
    "soldiers -- fiction",
    "solitude",
    "southern life",
    "strangers",
    "suicide victims",
    "supervivencia",
    "survival",
    "teacher-student relationships",
    "teenage boy/girl relations",
    "teenage girls",
    "terminally ill",
    "terminally ill—fiction",
    "therapeutic use",
    "tiere",
    "traffic accidents",
    "transsexuals",
    "trees",
    "triangles (interpersonal relations)",
    "tutela",
    "tutelle et curatelle",
    "uncles",
    "uncles, fiction",
    "unintended consequences",
    "united nations",
    "violence",
    "whitman college",
    "wishes",
    "women",
    "women and literature",
    "women hermits",
    "women journalists",
    "women poets",
    "women rock musicians",
    "writers",
    "young adults",
    "young men",
    "young women",
    "young women, fiction",
    "youthfulness",
    # --- LOCATION TAGS (NOT GENRES) ---
    "london (england), fiction",
    "england, fiction",
    "africa, fiction",
    "italy, fiction",
    "iowa, fiction",
    "north carolina, fiction",
    "northern ireland, fiction",
    "massachusetts, fiction",
    "dublin (ireland)",
    "dublin (ireland), fiction",
    "sicily (italy), fiction",
    "indiana, fiction",
    "jalisco (méxico)",
    "england in fiction",
    "france in fiction",
    "mexico, fiction",
    "vermont, fiction",
    "united states, fiction",
    "france",
    "india",
}


GLOBAL_AVERAGES = {
    "avg_books_per_year": 7,
    "avg_book_length_pages": 340,
    "avg_publish_year": 2009,
}

# Create a reverse mapping for fast lookups (alias -> canonical).
CANONICAL_GENRE_MAP = {}
for canonical, aliases in GENRE_ALIASES.items():
    CANONICAL_GENRE_MAP[canonical] = canonical
    for alias in aliases:
        CANONICAL_GENRE_MAP[alias] = canonical
