# dna_constants.py

"""
This file stores the constant data used by the Reading DNA generator.
This is the final, comprehensive version incorporating extensive user feedback.
"""


READER_TYPE_DESCRIPTIONS = {
    "Fantasy Fanatic": [
        "You have a deep love for worlds of magic, myth, and epic quests. Your reading history is filled with fantasy and science fiction.",
        "Your library is a gateway to other realms. You consistently choose books in the fantasy and sci-fi genres.",
        "From dragons to distant galaxies, your reading habits show a clear preference for the imaginative and the speculative.",
    ],
    "Novella Navigator": [
        "You're a master of the short-form narrative, frequently choosing books under 200 pages. You appreciate a story that gets straight to the point.",
        "Your reading data shows a strong preference for shorter books. You enjoy concise, impactful stories that can be read in a single sitting.",
        "You've read a significant number of novellas and shorter works, making you an expert in the art of brevity.",
    ],
    "Small Press Supporter": [
        "You champion the underdogs of the publishing world. A significant portion of your reading comes from independent and small presses.",
        "Your library is filled with hidden gems from outside the major publishing houses. You have a keen eye for unique, independent voices.",
        "By frequently reading books from small presses, you actively support a more diverse literary landscape.",
    ],
    "Tome Tussler": [
        "You aren't afraid of commitment. Your reading history is filled with massive books over 500 pages long.",
        "You love to get lost in sprawling epics and complex narratives, as shown by the number of lengthy tomes you've conquered.",
        "Your results show a clear pattern of tackling the biggest books on the shelf. You're a true heavyweight reader.",
    ],
    "Classic Collector": [
        "You have a great appreciation for the classics. A notable part of your reading list was published before 1970.",
        "Your reading habits show a journey through literary history, with a strong focus on timeless, classic works.",
        "You frequently read books that have stood the test of time, building a library of foundational literary classics.",
    ],
    "Versatile Valedictorian": [
        "Your reading tastes are incredibly diverse. You've explored a wide array of genres, from fiction to non-fiction and everything in between.",
        "You are a true literary explorer. Your results show you've read from more than ten distinct canonical genres.",
        "Your library is a testament to your curiosity, spanning a broad and impressive range of different literary categories.",
    ],
    "Non-Fiction Ninja": [
        "You read to learn and understand the world. Your library is heavily weighted towards non-fiction titles.",
        "From history to science to biography, your reading habits show a strong desire for facts, insights, and real-world knowledge.",
    ],
    "Social Savant": [
        "You are fascinated by the dynamics of society. Your reading list is rich with books on sociology, politics, and current events.",
        "Your library reflects a deep engagement with social structures and human behavior, focusing on the social sciences.",
    ],
    "Modern Maverick": [
        "You have your finger on the pulse of modern literature. You consistently read new releases and books published in the last few years.",
        "Your bookshelf is a snapshot of the current literary moment, showing a strong preference for contemporary authors and recent publications.",
    ],
    "Philosophical Philomath": [
        "You enjoy pondering the big questions. Your reading history shows a recurring interest in philosophical works.",
        "Your library is a space for deep thought, filled with books that explore ethics, existence, and the nature of reality.",
    ],
    "Eclectic Reader": [
        "Your reading habits are balanced and wide-ranging, with no single trait dominating the others. You are a true eclectic reader!",
    ],
}


# This new hierarchical dictionary replaces the old MAJOR_PUBLISHERS set.
MAINSTREAM_PUBLISHERS_HIERARCHY = {
    "Penguin Random House": [
        "Penguin Books",
        "Random House",
        "Viking Press",
        "G. P. Putnam's Sons",
        "Knopf Doubleday",
        "Crown Publishing",
        "Ballantine Books",
        "Bantam Dell",
        "Dutton",
        "Berkley",
        "Riverhead Books",
        "Vintage Books",
        "Anchor Books",
        "Signet",
    ],
    "Hachette Livre": [
        "Hachette",
        "Grand Central Publishing",
        "Little, Brown and Company",
        "Orbit Books",
        "Orion Publishing Group",
        "Perseus Books Group",
    ],
    "HarperCollins": [
        "Harper",
        "William Morrow",
        "Avon Books",
        "Harlequin Enterprises",
        "Ecco Press",
        "Harvill Secker",
    ],
    "Macmillan Publishers": ["Macmillan", "Farrar, Straus and Giroux", "St. Martin's Press", "Tor Books", "Picador"],
    "Simon & Schuster": ["Simon and Schuster", "Scribner", "Atria Books", "Gallery Books"],
    # Other Major Standalones
    "Bloomsbury Publishing": ["Bloomsbury"],
    "Scholastic Corporation": ["Scholastic"],
    "Oxford University Press": ["Oxford University Press"],
    "Pearson Education": ["Pearson Education", "Prentice Hall"],
    "John Wiley & Sons": ["Wiley"],
    "Routledge": ["Routledge"],
    "Grove Atlantic": ["Grove Press"],
}

GENRE_ALIASES = {
    # --- FICTION ---
    "fantasy": {
        "fantasy fiction",
        "epic fantasy",
        "high fantasy",
        "wizards",
        "magic",
        "urban fantasy",
        "magical realism",
        "dragons",
        "discworld (imaginary place)",
        "shapeshifting",
        "english fantasy fiction",
        "american fantasy fiction",
        "fiction, fantasy, epic",
        "mundodisco (lugar imaginario)",
        "novela fantástica",
        "wizards, fiction",
        "magic, fiction",
        "disque-monde (lieu imaginaire)",
        "discworld",
        "giants",
        "knights",
        "quests",
        "fiction, fantasy, general",
        "knights and knighthood",
        "fantastique",
        "quests (expeditions)",
        "discworld (imaginary place",  # Typo fix
        "adventure fiction",
        "epic literature",
    },
    "science fiction": {
        "sci-fi",
        "speculative fiction",
        "dystopian fiction",
        "cyberpunk",
        "space opera",
        "time travel",
        "science fiction, american",
        "utopias",
        "the future",
        "artificial intelligence",
        "totalitarianism",
        "hainish cycle",
        "dune (imaginary place)",
        "science-fiction",
        "fiction, dystopian",
        "dystopias",
        "totalitarianism -- fiction",
        "robots",
    },
    "thriller": {
        "thriller",
        "mystery fiction",
        "crime fiction",
        "suspense fiction",
        "assassins",
        "detective and mystery stories",
        "thrillers (fiction)",
        "spy stories",
        "crime",
        "mystery",
        "murder",
        "murderers",
        "fiction, crime",
        "theft",
        "assassination",
        "fiction, thrillers",
        "detectives",
        "criminal investigation",
        "revenge",
        "crime, fiction",
        "prisons / fiction",
        "brigands and robbers",
        "fiction, thrillers, general",
        "investigation",
        "malicious accusation",
        "mystery and detective stories",
        "adventure stories",
        "suspense",
        "espionage",
        "adventure and adventurers",
    },
    "horror": {
        "horror fiction",
        "ghost stories",
        "supernatural fiction",
        "gothic fiction",
        "fiction, gothic",
        "supernatural",
        "southern gothic",
        "monsters",
        "horror stories",
        "horror tales",
        "fiction, horror",
        "hell",
        "histoires de fantômes",
        "novela de terror",
        "witches",
        "gothic literature",
        "occult fiction",
        "fiction, ghost",
        "paranormal fiction",
        "fiction, fantasy, paranormal",
        "irish occult fiction",
    },
    "historical fiction": {
        "historical fiction",
        "roman historique",
        "world war, 1914-18",
        "world war, 1939-45",
        "trojan war",
        "fiction, historical, general",
        "fiction / historical",
        "rome, fiction",
        "war stories",
        "world war i",
        "world war ii",
        "fiction, historical",
        "spain, fiction",
        "greece, fiction",
        "france in fiction",
        "world war, 1914-1918",
        "world war, 1939-1945",
        "princes, fiction",
        "napoleonic wars",
        "battle of waterloo",
        "french revolution",
        "american civil war",
        "nazi germany",
        "soviet union",
        "great depression",
        "great depression, 1929-1939",
    },
    "romance": {
        "romance fiction",
        "love stories",
        "contemporary romance",
        "love",
        "love—fiction",
        "love stories, english",
        "fiction, romance, contemporary",
        "courtship",
        "first loves",
        "fiction, romance, general",
        "gay love",
        "english love stories",
        "romance",
        "man-woman relationship",
        "relationships",
    },
    "humorous fiction": {
        "humorous stories",
        "humor",
        "satire",
        "political satire",
        "fiction, satire",
        "humor.",
        "fiction, humorous",
    },
    "young adult": {
        "young adult fiction",
        "juvenile literature",
        "ya",
        "juvenile",
        "teenage fiction",
        "high school students",
        "coming of age",
        "adolescence",
        "runaway teenagers",
        "teenage boys",
        "youth, fiction",
    },
    "children's literature": {
        "children's stories",
        "picture books",
        "boys",
        "children's plays",
        "children's plays, english",
    },
    "classics": {
        "classic",
        "classical literature",
        "fiction classics",
        "classic fiction",
        "classic literature",
    },
    "mythology & folklore": {
        "mythology",
        "retellings",
        "gods",
        "folklore",
        "literature: folklore/mythology",
        "fiction / folklore",
        "achilles (mythological character)",
        "achilles (greek mythology)",
        "iphigenia (greek mythology)",
        "thetis",
        "epic poetry",
        "greek epic poetry",
        "classical epic poetry",
        "legends",
        "fairy tales",
        "legends, fiction",
        "prophecies",
        "prophecy",
        "epic",
        "god and goddesses",
        "demons",
    },
    "short stories": {"short stories", "english short stories", "short story"},
    "comics & graphic novels": {
        "cartoons and comics",
        "graphic novels",
        "comic books, strips",
    },
    "holiday fiction": {"christmas stories"},
    "fairy tales & fables": {"fairy tales", "fables", "fairy tale fiction"},
    # --- NON-FICTION ---
    "non-fiction": {"nonfiction", "essays", "journalism", "creative nonfiction", "doctrines"},
    "biography": {
        "biography",
        "autobiography",
        "memoir",
        "biographies",
        "memoirs",
        "diaries",
        "fiction, biographical",
        "biography & autobiography",
        "authors, biography",
        "cancer, patients, biography",
        "terminally ill, biography",
        "fiction / biographical",
    },
    "history": {
        "history",
        "world history",
        "ancient history",
        "military history",
        "historia",
        "explosives",
        "munitions",
    },
    "psychology": {
        "mental health",
        "psychology",
        "psychological fiction",
        "evolutionary psychology",
        "fiction, psychological",
        "genetic psychology",
        "behavior evolution",
        "american psychological fiction",
        "mental illness",
        "neuropsychology",
        "cognitive neuroscience",
        "fiction / psychological",
        "recollection (psychology)",
        "aversion therapy",
        "behavior",
        "psychological aspects",
        "degeneration",
        "multiple personality",
    },
    "philosophy": {
        "philosophy",
        "ethics",
        "metaphysics",
        "stoicism",
        "existentialism",
        "good and evil",
        "ancient philosophy",
        "philosophy, ancient",
        "philosophy, christian",
        "fate and fatalism",
        "existentialism in literature",
        "aristotle",
        "appearance (philosophy)",
        "filosofia antiga",
        "filosofia grega",
    },
    "social science": {
        "sociology",
        "politics",
        "social history",
        "anthropology",
        "current events",
        "fiction, political",
        "political science",
        "feminism",
        "feminist theory",
        "feminist ethics",
        "social control",
        "popular culture",
        "race relations",
        "african american studies",
        "social classes, fiction",
        "ethnic studies",
        "pornography, social aspects",
        "racial segregation",
        "women, social conditions",
        "equality",
        "city planning",
        "consumption",
        "feminism and literature",
        "feminist fiction, english",
        "sex role",
    },
    "nature": {
        "natural history",
        "environment",
        "animals",
        "outdoors",
        "nature writing",
        "biology",
        "country life",
        "dogs, fiction",
        "animals, fiction",
        "zoologists",
        "resource conservation",
        "human-animal relationships",
        "human-animal communication",
        "fishing stories",
        "horses",
        "cats, fiction",
        "rabbits",
    },
    "self-help": {
        "self-help",
        "personal development",
        "self-improvement",
        "productivity",
        "business",
        "self-actualization (psychology)",
        "maturity",
        "conduct of life",
        "conduct of life, fiction",
    },
    "science": {
        "science",
        "popular science",
        "physics",
        "astronomy",
        "biological evolution",
        "cosmology",
        "astrophysics",
        "brain",
        "neurology",
        "hallucinogenic drugs",
    },
    "travel": {
        "travel writing",
        "travelogue",
        "voyages and travels",
        "description and travel",
        "imaginary voyages",
        "explorers",
        "discovery and exploration",
        "globetrotter",
    },
    "art & music": {
        "art",
        "art appreciation",
        "visual perception",
        "music",
        "photograph collections",
        "musicians",
        "women rock musicians",
        "portraits",
        "technique",
        "beethoven's fifth symphony",
        "trees in art",
    },
    "food & cooking": {
        "cooking",
        "food",
        "nutrition",
        "eating",
        "cooking & food",
        "cooking methods",
        "food habits",
        "tea",
        "japanese tea ceremony",
        "chadō",
    },
    "plays & drama": {
        "plays / drama",
        "play",
        "plays",
        "english drama",
        "motion picture plays",
        "animal drama",
        "performing arts",
        "french drama",
        "drama (dramatic works by one author)",
        "drama",
        "theater",
        "readers' theater",
        "juvenile drama",
        "theater programs",
        "drama, history and criticism",
    },
    "religion & spirituality": {
        "bible",
        "christianity",
        "catholic church",
        "angels",
        "antichrist",
        "religion",
        "religious",
        "fiction, religious",
    },
}

EXCLUDED_GENRES = {
    # --- LIBRARY OF CONGRESS / DEWEY DECIMAL ---
    "813/.54",
    "823/.6",
    "pr5841.w8 m37 2007",
    "185",
    # --- AWARDS / METADATA ---
    "award:hugo_award=1966",
    "award:hugo_award=novel",
    "award:man_booker_prize=1997",
    "award:nebula_award=novel",
    "hugo award winner",
    "reading level-grade 7",
    "facsimiles",
    "new york times bestseller",
    "protected DAISY",
    "textual criticism",
    "reference",
    "open_syllabus_project",
    "bibliography",
    "catalogs",
    "congresses",
    "promptbooks",
    "special collections",
    "gift books",
    "in library",
    "overdrive",
    "large type books",
    "appreciation",
    "literary criticism",
    "twentieth century",
    # --- LANGUAGES / TRANSLATIONS / NATIONALITIES (NOT GENRES) ---
    "translations into english",
    "french literature",
    "american literature",
    "english fiction",
    "french fiction",
    "fiction in spanish",
    "french language materials",
    "spanish language",
    "english language",
    "language and languages",
    "translations into irish",
    "translations into italian",
    "translations into russian",
    "american authors",
    "english authors",
    "french language",
    "french language books",
    "amerikanisches englisch",
    "ameriška književnost",
    "družbene razmere",
    "dénonciation calomnieuse",
    "medosebni odnosi",
    "morale ancienne",
    "ouvrages avant 1800",
    "rappel (psychologie)",
    "sociale evolutie",
    "v leposlovju",
    "verhaltensforschung",
    # --- SIMPLE / BROAD EXCLUSIONS ---
    "fiction",
    "literature",
    "ficción",
    "fiction, general",
    "romans, nouvelles",
    "english literature",
    "juvenile fiction",
    "children's fiction",
    "general",
    "fiction / general",
    "fictional works",
    "literary",
    "british fiction",
    "fiction - general",
    "academic",
    "crap",
    # Additional broad exclusions to prevent false matches
    "continental european fiction",
    "european fiction",
    "american fiction",
    "contemporary fiction",
    "modern fiction",
    "historical",
    "social",
    "cultural",
    # --- THEMES / SUBJECTS / CHARACTERS (WHAT A BOOK IS ABOUT, NOT WHAT IT IS) ---
    "abandoned children",
    "adoptees, fiction",
    "african american women",
    "african-americans",
    "alienation in teenagers",
    "alternative family",
    "american poets",
    "ancianos",
    "antoine (marcus antonius)",
    "asperger's syndrome",
    "authorship",
    "autism",
    "black people",
    "boarding schools",
    "books and reading",
    "bulls",
    "businesswomen",
    "campesinos",
    "cancer, fiction",
    "cancer—fiction",
    "catch-22 (heller, joseph)",
    "cats",
    "cemeteries",
    "chelsea hotel",
    "child rearing",
    "classicists",
    "college students",
    "college teachers",
    "contemporary women",
    "country homes",
    "cousins",
    "cousins, fiction",
    "curiosities and wonders",
    "dalit",
    "dancers",
    "dating & sex",
    "death",
    "death, grief, bereavement",
    "discoveries in geography",
    "diseases",
    "dogs",
    "dwellings",
    "economic conditions",
    "ehemann",
    "elderly",
    "emperors",
    "english life",
    "english teachers",
    "etiquette",
    "expedition",
    "families",
    "family life",
    "family relations",
    "family relationships",
    "fathers and daughters",
    "female friendship",
    "feminists",
    "femmes",
    "femmes écrivains",
    "fighting bull",
    "fishers",
    "frankenstein (fictitious character)",
    "fraternal twins",
    "friendship",
    "fugitives from justice",
    "gang rape",
    "gond (indic people)",
    "greeks",
    "grief",
    "guardian and ward",
    "guards troops",
    "guilt",
    "health",
    "heart",
    "high school seniors",
    "hispanic americans, fiction",
    "hombres",
    "homme",
    "hp lovecraft",
    "human beings",
    "husband and wife",
    "illegal alien children",
    "immigrant children",
    "immigrants",
    "interpersonal relations",
    "interpersonal relations, fiction",
    "japan",
    "japanese",
    "labor trilogy",
    "labyrinths",
    "life change events",
    "livres et lecture",
    "love",
    "male friendship",
    "man",
    "man-woman relationships",
    "manners",
    "marital conflict",
    "marriage",
    "marriage, fiction",
    "married people",
    "married people, fiction",
    "married women",
    "mate selection",
    "medication abuse",
    "memory",
    "men",
    "mentally ill women",
    "middle-aged women",
    "missing persons",
    "mistresses",
    "mob mentality",
    "mortality",
    "mothers",
    "mothers and daughters",
    "motion picture industry",
    "moški in ženske",
    "mujeres",
    "musicians",
    "musicians, fiction",
    "médicos",
    "neighbors",
    "neurosurgeons",
    "nigerians",
    "nobility in fiction",
    "nursing homes",
    "older people",
    "opioid abuse",
    "orphans",
    "parental influences",
    "patients",
    "peasants",
    "photographers",
    "photographers, fiction",
    "physicians",
    "physicians in fiction",
    "physicians, fiction",
    "planned communities",
    "poor families",
    "poor families, fiction",
    "pornography",
    "poverty",
    "poverty -- fiction",
    "preparatory school students",
    "preparatory schools",
    "princes",
    "prisons",
    "private schools",
    "psychiatric hospitals",
    "psychotherapy patients",
    "pyramids",
    "pyramids -- fiction.",
    "quacks and quackery",
    "race",
    "readers",
    "rebellion",
    "refugees",
    "reincarnation",
    "revenge",
    "rich people",
    "riot grrrl movement",
    "rock musicians",
    "sailors",
    "savants (savant syndrome)",
    "schools",
    "scientists",
    "scientists, fiction",
    "self-destructive behavior",
    "self-experimentation in medicine",
    "sex",
    "sexual minority culture",
    "shame",
    "single-parent families",
    "sisters",
    "smith, patti, 1946-",
    "social aspects",
    "social conditions",
    "social isolation",
    "social themes",
    "soldiers",
    "soldiers -- fiction",
    "solitude",
    "southern life",
    "strangers",
    "suicide victims",
    "supervivencia",
    "survival",
    "teacher-student relationships",
    "teenage boy/girl relations",
    "teenage girls",
    "terminally ill",
    "terminally ill—fiction",
    "therapeutic use",
    "tiere",
    "traffic accidents",
    "transsexuals",
    "trees",
    "triangles (interpersonal relations)",
    "tutela",
    "tutelle et curatelle",
    "uncles",
    "uncles, fiction",
    "unintended consequences",
    "united nations",
    "violence",
    "whitman college",
    "wishes",
    "women",
    "women and literature",
    "women hermits",
    "women journalists",
    "women poets",
    "women rock musicians",
    "writers",
    "young adults",
    "young men",
    "young women",
    "young women, fiction",
    "youthfulness",
    # --- LOCATION TAGS (NOT GENRES) ---
    "london (england), fiction",
    "england, fiction",
    "africa, fiction",
    "italy, fiction",
    "iowa, fiction",
    "north carolina, fiction",
    "northern ireland, fiction",
    "massachusetts, fiction",
    "dublin (ireland)",
    "dublin (ireland), fiction",
    "sicily (italy), fiction",
    "indiana, fiction",
    "jalisco (méxico)",
    "england in fiction",
    "france in fiction",
    "mexico, fiction",
    "vermont, fiction",
    "united states, fiction",
    "france",
    "india",
    # ---
    "comic books, strips, etc",
    "in literature",
    "examinations -- study guides",
    "examinations",
    "examinations - study guides",
    "man-woman relationships",
    "plantation life",
    "frontier and pioneer life",
    "married people",
    "success",
    "men",
    "women",
    "rich people",
    "upper class families",
    # Additional exclusions from enrichment analysis
    "continental european fiction (fictional works by one author)",
    "american fiction (fictional works by one author)",
    "fictional works by one author",
    "ficture (fictional works by one author)",
    "british and irish fiction (fictional works by one author)",
    "novela",
    "novels",
    "roman",
    "romans",
    "romans, nouvelles",
    "drama",
    "drama (dramatic works by one author)",
    "adventure stories",
    "coming-of-age",
    "erotic fiction",
    "literary fiction",
    "short stories",
    "children's books",
    "audiobooks",
    "electronic books",
    "large print books",
    "reference books",
    "study guides",
    "adaptations",
    "film and video adaptations",
    "characters",
    "fiction subjects",
    "location tags",
    # Language tags
    "english",
    "french",
    "german",
    "spanish",
    "ficción juvenil",
    "ficción",
    "novela fantástica",
    # Character/topic subjects not genres
    "vampires",
    "vampiros",
    "leones",
    "lions",
    "lion",
    "winter",
    "the blitz",
    "fauns",
    "turkish delight",
    "good and evil",
    "bien y mal",
    "end of the world",
    "apocalypse",
    "fin du monde",
    "humorous",
    "proféties",
    # Relationship/theme subjects
    "father-son relationship",
    "brothers and sisters",
    "brothers and sisters, fiction",
    "brothers and sisters--fiction",
    "jealousy",
    "revenge",
    "affront",
    "truth",
    "loyalty",
    "loyauté",
    "vengeance",
    "depravity",
    "beneficence",
    "the struggle for acceptance",
    "self-destruction",
    "twins",
    "sibling rivalry",
    "rivaldad entre hermanos",
    "conflict management",
    "moral and ethical aspects",
    "respect for persons",
    "moral formation",
    "character formation",
    "youthfulness",
    "romance norte americano",
    "spiritual life",
    "immortality",
    "aging",
    "freedom",
    "redemption",
    "bread",
    "nervous system",
    "nervous system--wounds and injuries",
    "nervous system--wounds and injuries--fiction",
    "pirates",
    "burial",
    "burial--fiction",
    "soul",
    "hedonism",
    "fate and fatalism",
    "fate",
    "painting, fiction",
    "painting",
    "creativity",
    "wealth",
    "riches",
    "pauvre",
    "poor",
    "agronomists",
    "farm life",
    "ranch life",
    "california",
    "oklahoma",
    "mississippi",
    "dust bowl era, 1931-1939",
    "great depression, 1929-1939",
    "depressions",
    "depressions--fiction",
    "agricultural laborers",
    "farm family",
    "rural families",
    "rural families--fiction",
    # Domestic/household themes  
    "epic fiction",
    "novela hogareña",
    # More specific exclusions from enrichment logs
    "open library staff picks",
    "international relations",
    "adventure",
    "music",
    "revenge",
    "school",
    "best sellers",
    "novelists",
    "women authors, american",
    # Award tags
    "award:hugo_award=1960",
    "award:hugo_award=1962",
    "award:hugo_award=1970",
    "award:hugo_award=1974",
    "award:hugo_award=1975",
    "award:hugo_award=1985",
    "award:hugo_award=1986",
    "award:hugo_award=1990",
    "award:hugo_award=2002",
    "award:hugo_award=2016",
    "award:hugo_award=novel",
    "award:nebula_award=novel",
    "award:pulitzer_prize=1940",
    "award:pulitzer_prize=fiction",
    "hugo award winner",
    "nebula award winner",
    "pulitzer prize winner",
    "hugo award",
    "nebula award",
    "stonewall book awards",
    "quill award",
    "alex award",
    "new york times bestseller",
    "new york times reviewed",
    # Reading levels
    "reading level-grade 7",
    "reading level-grade 8",
    "reading level-grade 9",
    "reading level-grade 10",
    "reading level-grade 11",
    "reading level-grade 12",
    # Character names and fictional places
    "frodo baggins (fictitious character)",
    "baggins, frodo (fictitious character)",
    "gandalf (fictitious character)",
    "gollum (fictitious character)",
    "bilbo baggins (fictitious character)",
    "captain ahab (fictitious character)",
    "ahab, captain (fictitious character)",
    "molly bloom (fictitious character)",
    "leopold bloom (fictitious character)",
    "daisy buchanan (fictitious character)",
    "jordan baker (fictitious character)",
    "harry potter (fictional character)",
    "frodo",
    "gandalf",
    "harry potter",
    "darth vader",
    "luke skywalker",
    "ender wiggin (fictitious character)",
    "wiggin, ender (fictitious character)",
    "peter wiggin (fictitious character)",
    "bean (fictitious character : card)",
    "rand al'thor (fictitious character)",
    "rand al'thor (fictitious character)",
    # Fictional places and objects
    "narnia (imaginary place)",
    "middle earth (imaginary place)",
    "yoknapatawpha county (imaginary place)",
    "dune (imaginary place)",
    "seven kingdoms (imaginary place)",
    "battle school (imaginary place)",
    "matrix (imaginary place)",
    "rama (imaginary space vehicle)",
    # Literary style/subgenre terms (not genres)
    "southern gothic",
    "urban fantasy",
    "high fantasy",
    "epic fantasy",
    # Collection tags
    "collection:eanes challenge",
    "collection:bannedbooks",
    "collection:conroechallenge",
    "collection:name",
    "collection:otherwise_tiptree_award",
    "collection:otherwise_tiptree_award=retroaward",
    "collection:otherwise_tiptree_award=retrohonor",
    "1000blackgirlbooks",
    "open_syllabus_project",
    "great_books_of_the_western_world",
    "national black family month",
    # More topic subjects that aren't genres
    "brothels",
    "gangsters",
    "swindlers and swindling",
    "orphans",
    "robbers and outlaws",
    "prophets",
    "battles",
    "sorcery",
    "empire",
    "malazan",
    "kidnapping",
    "parental kidnapping",
    "earthquake zones",
    "geographical myths",
    "complex (psychology)",
    "drama",
    "slavery",
    "communism",
    "german",
    "literary collections",
    "coloring books",
    "detective and mystery stories",
    # Google Books categories that aren't meaningful genres
    "brigands and robbers",
    "future life",
    "imaginary wars and battles",
    "reference",
    "life on other planets",
    # Comics/graphic novel compound terms from Open Library that are too specific
    "comics & graphic novels, fantasy",
    "comics & graphic novels, general",
    "comics & graphic novels, literary",
    "comics & graphic novels, adaptations",
    "comic books, strips",
    "migrant agricultural laborers--california--fiction",
    "labor camps--california--fiction",
    "migrant agricultural laborers--fiction",
    "labor camps--fiction",
    "depressions--fiction",
    "social conditions",
    "poor families",
    "poor families, fiction",
    "social problems",
    "temples",
    "tolerance",
    "racial relations",
    "ethnic relations",
    "lookalikes",
    "sosies",
    "siblings",
    "sisters",
    "brothers",
    "fraternal twins",
    "cousins",
    "cousins, fiction",
    "uncles",
    "uncles, fiction",
    "orphans",
    "orphans, fiction",
    "orphans in fiction",
    "homeless children",
    "runaway teenagers",
    "immigrant children",
    "illegal alien children",
    "adoptees, fiction",
    "abandoned children",
    "children of prostitutes",
    "patients",
    "terminally ill",
    "terminally ill--fiction",
    "cancer",
    "cancer, fiction",
    "cancer—fiction",
    "diseases",
    "health",
    "medical fiction",
    "medicine in literature",
    "physicians",
    "physicians in fiction",
    "physicians, fiction",
    "scientists",
    "scientists, fiction",
    "artists",
    "artists, fiction",
    "artists--fiction",
    "women poets",
    "american poets",
    "english teachers",
    "college teachers",
    "english teachers",
    "classicists",
    "ethnologists",
    "ethnologues",
    "photographers",
    "photographers, fiction",
    "rock musicians",
    "women rock musicians",
    "musicians",
    "musicians, fiction",
    "lawyers",
    "lawyers, fiction",
    "cooks",
    "sailors",
    "whalers (persons)",
    "guards troops",
    "photographers",
    "writers",
    "authors",
    "authorship",
    "american authors",
    "irish authors",
    "canadian authors",
    "women authors",
    "english authors",
    "french authors",
    "photographers",
    "women poets",
    "american poets",
    "english teachers",
    "college teachers",
    "english teachers",
    "classicists",
    "ethnologists",
    "ethnologues",
    "photographers",
    "photographers, fiction",
    "rock musicians",
    "women rock musicians",
    "musicians",
    "musicians, fiction",
    "lawyers",
    "lawyers, fiction",
    "cooks",
    "sailors",
    "whalers (persons)",
    "guards troops",
    "photographers",
    "writers",
    "authors",
    "authorship",
    "american authors",
    "irish authors",
    "canadian authors",
    "women authors",
    "english authors",
    "french authors",
    "young adults",
    "young men",
    "young women",
    "young women, fiction",
    "middle-aged women",
    "older people",
    "elderly",
    "ancianos",
    "médicos",
    "físicos",
    "photographers",
    "guards troops",
    # More exclusions from recent results
    "life on other planets",
    "habitable planets",
    "planets",
    "space colonies",
    "space colonies--fiction",
    "environmental engineering",
    "colonization",
    "terraforming",
    "nation building",
    "civil war",
    "imaginary places",
    "imaginary places, fiction",
    "seven kingdoms (imaginary place), fiction",
    "seven kingdoms (imaginary place)",
    "imaginary wars and battles",
    "guerras imaginarias",
    "rois et souverains",
    "reyes y soberanos",
    "kings and rulers",
    "rulers",
    "alchemy",
    "alquimia",
    "viajes",
    "traición",
    "betrayal",
    "refugees",
    "brothers",
    "frères",
    "guerres et batailles imaginaires",
    "dystopian",
    "series: a song of ice and fire",
    "narnia (imaginary place)",
    "narnia (imaginary place), fiction",
    "series",
    "demons",
    "homeless children",
    "antiheroes",
    "storytelling",
    "kvothe",
    "chandrian",
    "inn",
    "school",
    "university",
    "orphan",
    "frères et sœurs",
    "hermanos y hermanas",
    "hermanos",
    "siblings, fiction",
    "brothers and sisters",
    "brothers and sisters, fiction",
    "brothers and sisters--fiction",
    "siblings",
    "rape",
    "trials (rape)",
    "procesos por violación",
    "procès (viol)",
    "political refugees",
    "social conditions",
    "social life and customs",
    "mœurs et coutumes",
    "vida social y costumbres",
    "manners and customs",
    "poverty",
    "economic conditions",
    "working class",
    "upper class families",
    "aristocracy (social class)",
    "aristocracy (social class)--fiction",
    "slaves, fiction",
    "women slaves",
    "women slaves--fiction",
    "african americans, fiction",
    "african american women--fiction",
    "african american women cooks--fiction",
    "infanticide",
    "infanticide--fiction",
    "farm family",
    "rural families",
    "rural families--fiction",
    "rural families",
    "city and town life",
    "city and town life--fiction",
    "city and town life--fiction",
    "families",
    "family life",
    "family relations",
    "family relationships",
    "family secrets",
    "dysfunctional families",
    "problem families",
    "parent and adult child",
    "fathers and daughters",
    "fathers and daughters, fiction",
    "fathers and sons",
    "fathers and sons, fiction",
    "father-daughter relationship",
    "father-son relationship",
    "mothers and daughters",
    "married people",
    "married people, fiction",
    "married people--fiction",
    "husband and wife",
    "father and daughter",
    "parent and adult child",
    "attachment behavior",
    "parent-child relationship",
    "mother-child relationship",
    "father-child relationship",
    "children--fiction",
    "teenagers",
    "teenage girls",
    "teenage boys",
    "teenage boy/girl relations",
    "runaway teenagers",
    "alienation in teenagers",
    "high school seniors",
    "preparatory school students",
    "preparatory schools",
    "boarding schools",
    "private schools",
    "college students",
    "college teachers",
    "english teachers",
    "women slaves",
    "women slaves--fiction",
    "african americans",
    "african american women",
    "african american women cooks",
    "black people",
    "hispanic americans, fiction",
    "american national characteristics",
    "características nacionales",
    "national characteristics",
    "human beings",
    "death",
    "death, grief, bereavement",
    "death--fiction",
    "death in literature",
    "suicide",
    "suicide victims",
    "suicide victims in fiction",
    "suicide victims--fiction",
    "siblings",
    "sisters",
    "brothers",
    "fraternal twins",
    "cousins",
    "cousins, fiction",
    "uncles",
    "uncles, fiction",
    "orphans",
    "orphans, fiction",
    "orphans in fiction",
    "homeless children",
    "runaway teenagers",
    "immigrant children",
    "illegal alien children",
    "adoptees, fiction",
    "abandoned children",
    "children of prostitutes",
    "patients",
    "terminally ill",
    "terminally ill--fiction",
    "cancer",
    "cancer, fiction",
    "cancer—fiction",
    "diseases",
    "health",
    "medical fiction",
    "physicians",
    "physicians in fiction",
    "physicians, fiction",
    "scientists",
    "scientists, fiction",
    "artists",
    "artists, fiction",
    "artists--fiction",
    "women poets",
    "american poets",
    "english teachers",
    "college teachers",
    "english teachers",
    "classicists",
    "ethnologists",
    "ethnologues",
    "photographers",
    "photographers, fiction",
    "rock musicians",
    "women rock musicians",
    "musicians",
    "musicians, fiction",
    "lawyers",
    "lawyers, fiction",
    "cooks",
    "sailors",
    "whalers (persons)",
    "guards troops",
    "photographers",
    "writers",
    "authors",
    "authorship",
    "american authors",
    "irish authors",
    "canadian authors",
    "women authors",
    "english authors",
    "french authors",
    "young adults",
    "young men",
    "young women",
    "young women, fiction",
    "middle-aged women",
    "older people",
    "elderly",
    "ancianos",
    "médicos",
    "físicos",
    "photographers",
    "guards troops",
    "photographers",
    "women hermits",
    "writers",
    "authors",
    "authorship",
    "american authors",
    "irish authors",
    "canadian authors",
    "women authors",
    "english authors",
    "french authors",
    "photographers",
    "women poets",
    "american poets",
    "english teachers",
    "college teachers",
    "english teachers",
    "classicists",
    "ethnologists",
    "ethnologues",
    "photographers",
    "photographers, fiction",
    "rock musicians",
    "women rock musicians",
    "musicians",
    "musicians, fiction",
    "lawyers",
    "lawyers, fiction",
    "cooks",
    "sailors",
    "whalers (persons)",
    "guards troops",
    "photographers",
    "writers",
    "authors",
    "authorship",
    "american authors",
    "irish authors",
    "canadian authors",
    "women authors",
    "english authors",
    "french authors",
    "young adults",
    "young men",
    "young women",
    "young women, fiction",
    "middle-aged women",
    "older people",
    "elderly",
    "ancianos",
    "médicos",
    "físicos",
    "photographers",
    "guards troops",
}


GLOBAL_AVERAGES = {
    "avg_books_per_year": 7,
    "avg_book_length_pages": 340,
    "avg_publish_year": 2009,
}

# Create a reverse mapping for fast lookups (alias -> canonical).
CANONICAL_GENRE_MAP = {}
for canonical, aliases in GENRE_ALIASES.items():
    CANONICAL_GENRE_MAP[canonical] = canonical
    for alias in aliases:
        CANONICAL_GENRE_MAP[alias] = canonical
