# dna_constants.py

"""
This file stores the constant data used by the Reading DNA generator,
including publisher lists and genre mappings. This keeps the main logic
file clean and makes these lists easier to maintain.
"""


READER_TYPE_DESCRIPTIONS = {
    "Fantasy Fanatic": [
        "You have a deep love for worlds of magic, myth, and epic quests. Your reading history is filled with fantasy and science fiction.",
        "Your library is a gateway to other realms. You consistently choose books in the fantasy and sci-fi genres.",
        "From dragons to distant galaxies, your reading habits show a clear preference for the imaginative and the speculative.",
    ],
    "Novella Navigator": [
        "You're a master of the short-form narrative, frequently choosing books under 200 pages. You appreciate a story that gets straight to the point.",
        "Your reading data shows a strong preference for shorter books. You enjoy concise, impactful stories that can be read in a single sitting.",
        "You've read a significant number of novellas and shorter works, making you an expert in the art of brevity.",
    ],
    "Small Press Supporter": [
        "You champion the underdogs of the publishing world. A significant portion of your reading comes from independent and small presses.",
        "Your library is filled with hidden gems from outside the major publishing houses. You have a keen eye for unique, independent voices.",
        "By frequently reading books from small presses, you actively support a more diverse literary landscape.",
    ],
    "Tome Tussler": [
        "You aren't afraid of commitment. Your reading history is filled with massive books over 500 pages long.",
        "You love to get lost in sprawling epics and complex narratives, as shown by the number of lengthy tomes you've conquered.",
        "Your results show a clear pattern of tackling the biggest books on the shelf. You're a true heavyweight reader.",
    ],
    "Classic Collector": [
        "You have a great appreciation for the classics. A notable part of your reading list was published before 1970.",
        "Your reading habits show a journey through literary history, with a strong focus on timeless, classic works.",
        "You frequently read books that have stood the test of time, building a library of foundational literary classics.",
    ],
    "Versatile Valedictorian": [
        "Your reading tastes are incredibly diverse. You've explored a wide array of genres, from fiction to non-fiction and everything in between.",
        "You are a true literary explorer. Your results show you've read from more than ten distinct canonical genres.",
        "Your library is a testament to your curiosity, spanning a broad and impressive range of different literary categories.",
    ],
    "Non-Fiction Ninja": [
        "You read to learn and understand the world. Your library is heavily weighted towards non-fiction titles.",
        "From history to science to biography, your reading habits show a strong desire for facts, insights, and real-world knowledge.",
    ],
    "Social Savant": [
        "You are fascinated by the dynamics of society. Your reading list is rich with books on sociology, politics, and current events.",
        "Your library reflects a deep engagement with social structures and human behavior, focusing on the social sciences.",
    ],
    "Modern Maverick": [
        "You have your finger on the pulse of modern literature. You consistently read new releases and books published in the last few years.",
        "Your bookshelf is a snapshot of the current literary moment, showing a strong preference for contemporary authors and recent publications.",
    ],
    "Philosophical Philomath": [
        "You enjoy pondering the big questions. Your reading history shows a recurring interest in philosophical works.",
        "Your library is a space for deep thought, filled with books that explore ethics, existence, and the nature of reality.",
    ],
    # Add other types as needed
    "Eclectic Reader": [
        "Your reading habits are balanced and wide-ranging, with no single trait dominating the others. You are a true eclectic reader!",
    ],
}

MAJOR_PUBLISHERS = {
    # Original List
    "penguin",
    "random house",
    "harpercollins",
    "simon & schuster",
    "hachette",
    "macmillan",
    "knopf",
    "doubleday",
    "viking",
    "vintage",
    "scribner",
    "atriabooks",
    # Recommended Additions
    "little, brown",
    "bloomsbury",
    "farrar, straus & giroux",
    "bantam",
    "scholastic",
    "putnam",
    "dutton",
    "hodder",
    "collins",
    "oxford university press",
    "routledge",
    "prentice hall",
    "grove press",
    "virago",
    "gollancz",
    "harper",
    "harcourt",
    "faber",
    "dover",
    "tantor",
    "signet",
    "Atria Books",
    "Ballantine Books",
    "Orion Publishing Group",
    "Berkley",
    "Hogarth",
}


EXCLUDED_GENRES = {
    # Original & simple exclusions
    "fiction",
    "literature",
    "ficción",
    "fiction, general",
    "romans, nouvelles",
    "english literature",
    "juvenile fiction",
    "children's fiction",
    "large type books",
    "general",
    "fiction / general",
    "fictional works",
    # Metadata and Publishing Terms
    "translations into english",
    "bibliography",
    "in library",
    "catalogs",
    "congresses",
    "american authors",
    "french literature",
    "american literature",
    "overdrive",
    "english fiction",
    "new york times bestseller",
    "protected DAISY",
    "textual criticism",
    "reference",
    "study and teaching",
    "open_syllabus_project",
    "fiction in spanish",
    "french language materials",
    "spanish language",
    "crap",
    "criticism and interpretation",
    "textbooks",
    "promptbooks",
    # Thematic Tags (Crucial to Exclude)
    "interpersonal relations",
    "man-woman relationships",
    "families",
    "women",
    "love",
    "death",
    "female friendship",
    "friendship",
    "social aspects",
    "social conditions",
    "fathers and daughters",
    "brothers and sisters",
    "mothers and daughters",
    "family life",
    "grief",
    "solitude",
    "cancer",
    "terminally ill",
    "patients",
    "revenge",
    "sex",
    "mortality",
    "fatherhood",
    "shame",
    "guilt",
    # Location Tags (Not a genre)
    "london (england), fiction",
    "england, fiction",
    "africa, fiction",
    "italy, fiction",
    "iowa, fiction",
    "north carolina, fiction",
    "northern ireland, fiction",
    "massachusetts, fiction",
    # Miscellaneous Unmappable Items
    "readers",
    "boarding schools",
    "college students",
    "young women",
    "rich people",
    "immigrants",
    "refugees",
    "writers",
    "authors",
    "musicians",
    "artists",
    "scientists",
}

GENRE_ALIASES = {
    # --- FICTION ---
    "fantasy": {
        "fantasy fiction",
        "epic fantasy",
        "high fantasy",
        "wizards",
        "magic",
        "urban fantasy",
        "magical realism",
        "fables",
        "dragons",
        "discworld (imaginary place)",
        "shapeshifting",
        "english fantasy fiction",
        "american fantasy fiction",
        "fiction, fantasy, epic",
        "mundodisco (lugar imaginario)",
        "novela fantástica",
        "wizards, fiction",
        "magic, fiction",
        "disque-monde (lieu imaginaire)",
        "discworld",
        "giants",
        "knights",
    },
    "science fiction": {
        "sci-fi",
        "speculative fiction",
        "dystopian fiction",
        "cyberpunk",
        "space opera",
        "time travel",
        "science fiction, american",
        "utopias",
        "the future",
        "artificial intelligence",
        "totalitarianism",
        "hainish cycle",
        "dune (imaginary place)",
        "science-fiction",
        "fiction, dystopian",
        "dystopias",
        "totalitarianism -- fiction",
    },
    "thriller": {
        "thriller",
        "mystery fiction",
        "crime fiction",
        "suspense fiction",
        "assassins",
        "detective and mystery stories",
        "thrillers (fiction)",
        "spy stories",
        "crime",
        "mystery",
        "murder",
        "murderers",
        "fiction, crime",
        "theft",
        "assassination",
        "fiction, thrillers",
        "detectives",
        "criminal investigation",
        "revenge",
    },
    "horror": {
        "horror fiction",
        "ghost stories",
        "supernatural fiction",
        "gothic fiction",
        "fiction, gothic",
        "supernatural",
        "southern gothic",
        "monsters",
        "horror stories",
        "horror tales",
        "fiction, horror",
    },
    "historical fiction": {
        "historical fiction",
        "roman historique",
        "world war, 1914-1918",
        "world war, 1939-1945",
        "trojan war",
        "fiction, historical, general",
        "fiction / historical",
        "rome, fiction",
        "war stories",
        "world war i",
        "world war ii",
        "fiction, historical",
    },
    "romance": {
        "romance fiction",
        "love stories",
        "contemporary romance",
        "love",
        "love—fiction",
        "love stories, english",
        "fiction, romance, contemporary",
        "courtship",
        "first loves",
        "fiction, romance, general",
    },
    "humorous fiction": {"humorous stories", "humor", "satire", "political satire", "fiction, satire", "humor."},
    "young adult": {
        "young adult fiction",
        "juvenile literature",
        "ya",
        "juvenile",
        "teenage fiction",
        "high school students",
        "coming of age",
    },
    "children's literature": {"children's stories", "picture books", "boys", "children"},
    "classics": {"classic", "classical literature", "fiction classics", "classic fiction", "classic literature"},
    "literary fiction": {
        "bildungsroman",
        "bildungsromans",
        "diary novels",
        "epistolary fiction",
        "contemporary",
        "contemporary fiction",
        "modern fiction",
        "fiction, family life",
        "families",
        "fiction / literary",
        "fiction, women",
        "women's fiction",
        "man-woman relationships",
        "man-woman relationships, fiction",
        "female friendship",
        "friendship, fiction",
        "slice-of-life",
        "family",
        "fiction / sagas",
    },
    "mythology & folklore": {
        "mythology",
        "retellings",
        "gods",
        "folklore",
        "literature: folklore/mythology",
        "fiction / folklore",
        "achilles (mythological character)",
        "achilles (greek mythology)",
    },
    "short stories": {"short stories", "english short stories", "short story"},
    # --- NON-FICTION ---
    "non-fiction": {"nonfiction", "essays", "journalism", "creative nonfiction"},
    "biography": {
        "biography",
        "autobiography",
        "memoir",
        "biographies",
        "memoirs",
        "diaries",
        "fiction, biographical",
        "biography & autobiography",
        "authors, biography",
    },
    "history": {"history", "world history", "ancient history", "military history", "historia"},
    "psychology": {
        "mental health",
        "psychology",
        "psychological fiction",
        "evolutionary psychology",
        "fiction, psychological",
        "genetic psychology",
        "behavior evolution",
        "american psychological fiction",
        "mental illness",
        "neuropsychology",
        "cognitive neuroscience",
    },
    "philosophy": {
        "philosophy",
        "ethics",
        "metaphysics",
        "stoicism",
        "existentialism",
        "good and evil",
        "ancient philosophy",
        "philosophy, ancient",
        "philosophy, christian",
        "fate and fatalism",
    },
    "social science": {
        "sociology",
        "politics",
        "social history",
        "anthropology",
        "current events",
        "fiction, political",
        "political science",
        "economics",
        "feminism",
        "feminist theory",
        "feminist ethics",
        "social control",
        "popular culture",
    },
    "nature": {
        "natural history",
        "environment",
        "animals",
        "outdoors",
        "nature writing",
        "biology",
        "country life",
        "farm life",
        "dogs, fiction",
        "animals, fiction",
        "zoologists",
    },
    "self-help": {
        "self-help",
        "personal development",
        "self-improvement",
        "productivity",
        "business",
        "conduct of life",
        "self-actualization (psychology)",
    },
    "science": {
        "science",
        "popular science",
        "physics",
        "astronomy",
        "biological evolution",
        "cosmology",
        "astrophysics",
        "brain",
        "neurology",
    },
    "travel": {"travel writing", "travelogue", "voyages and travels", "description and travel", "imaginary voyages"},
    "art & music": {"art", "art appreciation", "visual perception", "music", "photograph collections", "musicians"},
    "food & cooking": {"cooking", "food", "nutrition", "eating", "cooking & food"},
    "plays & drama": {"drama", "plays / drama", "play", "plays", "english drama", "motion picture plays"},
}


# Create a reverse mapping for fast lookups (alias -> canonical).
# This logic now lives here with the data it depends on.
CANONICAL_GENRE_MAP = {}
for canonical, aliases in GENRE_ALIASES.items():
    CANONICAL_GENRE_MAP[canonical] = canonical
    for alias in aliases:
        CANONICAL_GENRE_MAP[alias] = canonical
