-- Auto-generated cleanup script for test CSV books
-- Covers all CSVs in docs/test-csvs/ (319 unique titles)
-- Usage: cat docs/test-csvs/cleanup.sql | docker-compose -f docker-compose.local.yml exec -T db psql -U bibliotype_user -d bibliotype_db

BEGIN;

-- Delete related records first (foreign keys)
DELETE FROM core_userbook WHERE book_id IN (
  SELECT id FROM core_book WHERE title IN (
  '1984',
  'A Burning',
  'A Master of Djinn',
  'A Memory Called Empire',
  'A Passage North',
  'A Psalm for the Wild-Built',
  'Abandoned Book',
  'Activation Degradation',
  'After World',
  'Afterlives',
  'Aftershocks',
  'Age of Vice',
  'All Fours',
  'All the Colors of the Dark',
  'All the Sinners Bleed',
  'American Gods',
  'Annie Bot',
  'Anxious People',
  'Apples Never Fall',
  'Babel',
  'Beautiful World Where Are You',
  'Beautyland',
  'Beloved',
  'Bewilderment',
  'Birnam Wood',
  'Black Cake',
  'Black Sun',
  'Blackouts',
  'Book Currently Reading',
  'Book Marked DNF',
  'Book On TBR',
  'Book With Half Star',
  'Book With Long Review',
  'Book With No ISBN',
  'Book With No ISBN At All',
  'Book With No Rating',
  'Bookshops & Bonedust',
  'Booth',
  'Boy Parts',
  'Brave New World',
  'Brood',
  'Cahokia Jazz',
  'Chain-Gang All-Stars',
  'Children of Time',
  'Circe',
  'Clark and Division',
  'Cloud Cuckoo Land',
  'Companion Piece',
  'Counterfeit',
  'Creation Lake',
  'Crime and Punishment',
  'Crook Manifesto',
  'Crossroads',
  'Crying in H Mart',
  'Dead Collections',
  'Demon Copperhead',
  'Detransition Baby',
  'Detransition, Baby',
  'Divine Rivals',
  'Dune',
  'Elder Race',
  'Elektra',
  'Emily Wilde''s Map of the Otherlands',
  'Empire of Pain',
  'Fahrenheit 451',
  'Fairy Tale',
  'Fangirl',
  'Fellowship Point',
  'Fevered Star',
  'Five Star Book',
  'Foundation',
  'Fourth Wing',
  'Frankenstein',
  'Freakonomics',
  'Gone Girl',
  'Good Omens',
  'Great Circle',
  'Hamnet',
  'Happy Place',
  'Harlem Shuffle',
  'Harrow the Ninth',
  'Heart of Darkness',
  'Hell Bent',
  'Hell Followed With Us',
  'Hello Beautiful',
  'Holly',
  'Homeland Elegies',
  'Horse',
  'House of Flame and Shadow',
  'How Beautiful We Were',
  'How High We Go in the Dark',
  'How the Word Is Passed',
  'I Have Some Questions for You',
  'I''m Glad My Mom Died',
  'I''m a Fan',
  'In the Lives of Puppets',
  'Interior Chinatown',
  'Intermezzo',
  'Intimacies',
  'Iron Flame',
  'It',
  'James',
  'Jane Eyre',
  'Karima Has No Room to Breathe',
  'Klara and the Sun',
  'Lake of Darkness',
  'Lapvona',
  'Leave the World Behind',
  'Legends & Lattes',
  'Lessons in Chemistry',
  'Liberation Day',
  'Light From Uncommon Stars',
  'Lone Women',
  'Lucy by the Sea',
  'Maame',
  'Malibu Rising',
  'Matrix',
  'Memorial Drive',
  'Mexican Gothic',
  'Mislaid in Parts Half-Known',
  'Moon Witch Spider King',
  'Moonbound',
  'My Brilliant Friend',
  'My Year of Rest and Relaxation',
  'Nettle & Bone',
  'Neuromancer',
  'Nightcrawling',
  'No One Is Talking About This',
  'Nona the Ninth',
  'Noor',
  'Normal People',
  'North Woods',
  'Olga Dies Dreaming',
  'One Hundred Years of Solitude',
  'One Last Stop',
  'Orbital',
  'Our Share of Night',
  'Our Wives Under the Sea',
  'Peaces',
  'Pineapple Street',
  'Piranesi',
  'Plutoshine',
  'Portrait of an Unknown Woman',
  'Poverty, by America',
  'Pride and Prejudice',
  'Project Hail Mary',
  'Prophet Song',
  'Quietly Hostile',
  'Rakesfall',
  'Razorblade Tears',
  'Remarkably Bright Creatures',
  'Run Rose Run',
  'Run Towards the Danger',
  'S.',
  'Sahara Special',
  'Saint Death''s Daughter',
  'Sammy Went to Oxford and All He Got Was a Bloody Book',
  'Sapiens',
  'Sea of Tranquility',
  'Service Model',
  'Sharks in the Time of Saviours',
  'She Is a Haunting',
  'She Who Became the Sun',
  'Shuggie Bain',
  'Slaughterhouse-Five',
  'Small Mercies',
  'Small Things Like These',
  'Some Desperate Glory',
  'Someone You Can Build a Nest In',
  'Sorrow and Bliss',
  'Sorrowland',
  'South to America',
  'Starter Villain',
  'Stay True',
  'Stella Maris',
  'Stolen by the Borrowed Night',
  'System Collapse',
  'The Adventures of Amina al-Sirafi',
  'The Alchemist',
  'The Anxious Generation',
  'The Archive Undying',
  'The Atlas Six',
  'The Bee Sting',
  'The Bees',
  'The Bell Jar',
  'The Blade Itself',
  'The Bone Shard Daughter',
  'The Book of Doors',
  'The Bound Worlds',
  'The Bruising of Qilwa',
  'The Bullet Swallower',
  'The Candy House',
  'The Cartographers',
  'The City in Glass',
  'The Covenant of Water',
  'The Curator',
  'The Daughter of Doctor Moreau',
  'The Deep',
  'The Deep Sky',
  'The Deluge',
  'The Doors of Eden',
  'The Echo Wife',
  'The Employees',
  'The Empress of Salt and Fortune',
  'The Every',
  'The Familiar',
  'The Fifth Season',
  'The Fox Wife',
  'The Foxglove King',
  'The Fraud',
  'The Frugal Wizard''s Handbook for Surviving Medieval England',
  'The Furrows',
  'The Galaxy, and the Ground Within',
  'The Ghost Orchid',
  'The God of the Woods',
  'The Goldfinch',
  'The Great Gatsby',
  'The Great Reclamation',
  'The Grief of Stones',
  'The Handmaid''s Tale',
  'The Heaven & Earth Grocery Store',
  'The Hobbit',
  'The House in the Cerulean Sea',
  'The House of Rust',
  'The Invisible Life of Addie LaRue',
  'The Island of Missing Trees',
  'The It Girl',
  'The Jasmine Throne',
  'The Kaiju Preservation Society',
  'The Last Tale of the Flower Bride',
  'The Last Thing He Told Me',
  'The Light Pirate',
  'The Lincoln Highway',
  'The Long Halloween',
  'The Lord of the Rings',
  'The Lost Apothecary',
  'The Luminous Dead',
  'The Maid',
  'The Maidens',
  'The Making of Another Major Motion Picture Masterpiece',
  'The Marriage Portrait',
  'The Memory Police',
  'The Mercy of Gods',
  'The Midnight Library',
  'The Mimicking of Known Successes',
  'The Ministry of Time',
  'The Mountain in the Sea',
  'The Name of the Wind',
  'The Netanyahus',
  'The Night Watchman',
  'The Oleander Sword',
  'The Once and Future Witches',
  'The Paradox Hotel',
  'The Passenger',
  'The Personal Librarian',
  'The Phoenix Keeper',
  'The Phoenix King',
  'The Pomegranate Gate',
  'The Practice House',
  'The Prophets',
  'The Rabbit Hutch',
  'The Removed',
  'The Road',
  'The Saint of Bright Doors',
  'The School for Good Mothers',
  'The Secret History',
  'The Sentence',
  'The Silent Patient',
  'The Silverblood Promise',
  'The Siren of Sussex',
  'The Spear Cuts Through Water',
  'The Stand',
  'The Starless Crown',
  'The Surviving Sky',
  'The Tainted Cup',
  'The Talisman',
  'The Terraformers',
  'The Three-Body Problem',
  'The Trees',
  'The Tusks of Extinction',
  'The Unmaking of June Farrow',
  'The Vanished Birds',
  'The Vanishing Half',
  'The Wager',
  'The Warm Hands of Ghosts',
  'The Warm Months',
  'The Water Outlaws',
  'The Way of Kings',
  'The Wings Upon Her Back',
  'The Women',
  'The World We Make',
  'Thornhedge',
  'To Kill a Mockingbird',
  'Tom Lake',
  'Tomorrow and Tomorrow and Tomorrow',
  'Tomorrow, and Tomorrow, and Tomorrow',
  'Toward Eternity',
  'Transcendent Kingdom',
  'Translation State',
  'Tress of the Emerald Sea',
  'Trust',
  'Under the Whispering Door',
  'Unfinished Book',
  'Unicode Title: Café Stories',
  'Upgrade',
  'Venomous Lumpsucker',
  'Vera Wong''s Unsolicited Advice for Murderers',
  'Vladimir',
  'Wandering Stars',
  'Want to Read',
  'When the Moon Hatched',
  'Whereabouts',
  'While Justice Sleeps',
  'Who Is Maud Dixon?',
  'Win Every Argument',
  'Witch King',
  'Yellowface',
  'You Like It Darker',
  'Young Mungo'
  )
);

DELETE FROM core_book_genres WHERE book_id IN (
  SELECT id FROM core_book WHERE title IN (
  '1984',
  'A Burning',
  'A Master of Djinn',
  'A Memory Called Empire',
  'A Passage North',
  'A Psalm for the Wild-Built',
  'Abandoned Book',
  'Activation Degradation',
  'After World',
  'Afterlives',
  'Aftershocks',
  'Age of Vice',
  'All Fours',
  'All the Colors of the Dark',
  'All the Sinners Bleed',
  'American Gods',
  'Annie Bot',
  'Anxious People',
  'Apples Never Fall',
  'Babel',
  'Beautiful World Where Are You',
  'Beautyland',
  'Beloved',
  'Bewilderment',
  'Birnam Wood',
  'Black Cake',
  'Black Sun',
  'Blackouts',
  'Book Currently Reading',
  'Book Marked DNF',
  'Book On TBR',
  'Book With Half Star',
  'Book With Long Review',
  'Book With No ISBN',
  'Book With No ISBN At All',
  'Book With No Rating',
  'Bookshops & Bonedust',
  'Booth',
  'Boy Parts',
  'Brave New World',
  'Brood',
  'Cahokia Jazz',
  'Chain-Gang All-Stars',
  'Children of Time',
  'Circe',
  'Clark and Division',
  'Cloud Cuckoo Land',
  'Companion Piece',
  'Counterfeit',
  'Creation Lake',
  'Crime and Punishment',
  'Crook Manifesto',
  'Crossroads',
  'Crying in H Mart',
  'Dead Collections',
  'Demon Copperhead',
  'Detransition Baby',
  'Detransition, Baby',
  'Divine Rivals',
  'Dune',
  'Elder Race',
  'Elektra',
  'Emily Wilde''s Map of the Otherlands',
  'Empire of Pain',
  'Fahrenheit 451',
  'Fairy Tale',
  'Fangirl',
  'Fellowship Point',
  'Fevered Star',
  'Five Star Book',
  'Foundation',
  'Fourth Wing',
  'Frankenstein',
  'Freakonomics',
  'Gone Girl',
  'Good Omens',
  'Great Circle',
  'Hamnet',
  'Happy Place',
  'Harlem Shuffle',
  'Harrow the Ninth',
  'Heart of Darkness',
  'Hell Bent',
  'Hell Followed With Us',
  'Hello Beautiful',
  'Holly',
  'Homeland Elegies',
  'Horse',
  'House of Flame and Shadow',
  'How Beautiful We Were',
  'How High We Go in the Dark',
  'How the Word Is Passed',
  'I Have Some Questions for You',
  'I''m Glad My Mom Died',
  'I''m a Fan',
  'In the Lives of Puppets',
  'Interior Chinatown',
  'Intermezzo',
  'Intimacies',
  'Iron Flame',
  'It',
  'James',
  'Jane Eyre',
  'Karima Has No Room to Breathe',
  'Klara and the Sun',
  'Lake of Darkness',
  'Lapvona',
  'Leave the World Behind',
  'Legends & Lattes',
  'Lessons in Chemistry',
  'Liberation Day',
  'Light From Uncommon Stars',
  'Lone Women',
  'Lucy by the Sea',
  'Maame',
  'Malibu Rising',
  'Matrix',
  'Memorial Drive',
  'Mexican Gothic',
  'Mislaid in Parts Half-Known',
  'Moon Witch Spider King',
  'Moonbound',
  'My Brilliant Friend',
  'My Year of Rest and Relaxation',
  'Nettle & Bone',
  'Neuromancer',
  'Nightcrawling',
  'No One Is Talking About This',
  'Nona the Ninth',
  'Noor',
  'Normal People',
  'North Woods',
  'Olga Dies Dreaming',
  'One Hundred Years of Solitude',
  'One Last Stop',
  'Orbital',
  'Our Share of Night',
  'Our Wives Under the Sea',
  'Peaces',
  'Pineapple Street',
  'Piranesi',
  'Plutoshine',
  'Portrait of an Unknown Woman',
  'Poverty, by America',
  'Pride and Prejudice',
  'Project Hail Mary',
  'Prophet Song',
  'Quietly Hostile',
  'Rakesfall',
  'Razorblade Tears',
  'Remarkably Bright Creatures',
  'Run Rose Run',
  'Run Towards the Danger',
  'S.',
  'Sahara Special',
  'Saint Death''s Daughter',
  'Sammy Went to Oxford and All He Got Was a Bloody Book',
  'Sapiens',
  'Sea of Tranquility',
  'Service Model',
  'Sharks in the Time of Saviours',
  'She Is a Haunting',
  'She Who Became the Sun',
  'Shuggie Bain',
  'Slaughterhouse-Five',
  'Small Mercies',
  'Small Things Like These',
  'Some Desperate Glory',
  'Someone You Can Build a Nest In',
  'Sorrow and Bliss',
  'Sorrowland',
  'South to America',
  'Starter Villain',
  'Stay True',
  'Stella Maris',
  'Stolen by the Borrowed Night',
  'System Collapse',
  'The Adventures of Amina al-Sirafi',
  'The Alchemist',
  'The Anxious Generation',
  'The Archive Undying',
  'The Atlas Six',
  'The Bee Sting',
  'The Bees',
  'The Bell Jar',
  'The Blade Itself',
  'The Bone Shard Daughter',
  'The Book of Doors',
  'The Bound Worlds',
  'The Bruising of Qilwa',
  'The Bullet Swallower',
  'The Candy House',
  'The Cartographers',
  'The City in Glass',
  'The Covenant of Water',
  'The Curator',
  'The Daughter of Doctor Moreau',
  'The Deep',
  'The Deep Sky',
  'The Deluge',
  'The Doors of Eden',
  'The Echo Wife',
  'The Employees',
  'The Empress of Salt and Fortune',
  'The Every',
  'The Familiar',
  'The Fifth Season',
  'The Fox Wife',
  'The Foxglove King',
  'The Fraud',
  'The Frugal Wizard''s Handbook for Surviving Medieval England',
  'The Furrows',
  'The Galaxy, and the Ground Within',
  'The Ghost Orchid',
  'The God of the Woods',
  'The Goldfinch',
  'The Great Gatsby',
  'The Great Reclamation',
  'The Grief of Stones',
  'The Handmaid''s Tale',
  'The Heaven & Earth Grocery Store',
  'The Hobbit',
  'The House in the Cerulean Sea',
  'The House of Rust',
  'The Invisible Life of Addie LaRue',
  'The Island of Missing Trees',
  'The It Girl',
  'The Jasmine Throne',
  'The Kaiju Preservation Society',
  'The Last Tale of the Flower Bride',
  'The Last Thing He Told Me',
  'The Light Pirate',
  'The Lincoln Highway',
  'The Long Halloween',
  'The Lord of the Rings',
  'The Lost Apothecary',
  'The Luminous Dead',
  'The Maid',
  'The Maidens',
  'The Making of Another Major Motion Picture Masterpiece',
  'The Marriage Portrait',
  'The Memory Police',
  'The Mercy of Gods',
  'The Midnight Library',
  'The Mimicking of Known Successes',
  'The Ministry of Time',
  'The Mountain in the Sea',
  'The Name of the Wind',
  'The Netanyahus',
  'The Night Watchman',
  'The Oleander Sword',
  'The Once and Future Witches',
  'The Paradox Hotel',
  'The Passenger',
  'The Personal Librarian',
  'The Phoenix Keeper',
  'The Phoenix King',
  'The Pomegranate Gate',
  'The Practice House',
  'The Prophets',
  'The Rabbit Hutch',
  'The Removed',
  'The Road',
  'The Saint of Bright Doors',
  'The School for Good Mothers',
  'The Secret History',
  'The Sentence',
  'The Silent Patient',
  'The Silverblood Promise',
  'The Siren of Sussex',
  'The Spear Cuts Through Water',
  'The Stand',
  'The Starless Crown',
  'The Surviving Sky',
  'The Tainted Cup',
  'The Talisman',
  'The Terraformers',
  'The Three-Body Problem',
  'The Trees',
  'The Tusks of Extinction',
  'The Unmaking of June Farrow',
  'The Vanished Birds',
  'The Vanishing Half',
  'The Wager',
  'The Warm Hands of Ghosts',
  'The Warm Months',
  'The Water Outlaws',
  'The Way of Kings',
  'The Wings Upon Her Back',
  'The Women',
  'The World We Make',
  'Thornhedge',
  'To Kill a Mockingbird',
  'Tom Lake',
  'Tomorrow and Tomorrow and Tomorrow',
  'Tomorrow, and Tomorrow, and Tomorrow',
  'Toward Eternity',
  'Transcendent Kingdom',
  'Translation State',
  'Tress of the Emerald Sea',
  'Trust',
  'Under the Whispering Door',
  'Unfinished Book',
  'Unicode Title: Café Stories',
  'Upgrade',
  'Venomous Lumpsucker',
  'Vera Wong''s Unsolicited Advice for Murderers',
  'Vladimir',
  'Wandering Stars',
  'Want to Read',
  'When the Moon Hatched',
  'Whereabouts',
  'While Justice Sleeps',
  'Who Is Maud Dixon?',
  'Win Every Argument',
  'Witch King',
  'Yellowface',
  'You Like It Darker',
  'Young Mungo'
  )
);

-- Delete the books themselves
DELETE FROM core_book WHERE title IN (
  '1984',
  'A Burning',
  'A Master of Djinn',
  'A Memory Called Empire',
  'A Passage North',
  'A Psalm for the Wild-Built',
  'Abandoned Book',
  'Activation Degradation',
  'After World',
  'Afterlives',
  'Aftershocks',
  'Age of Vice',
  'All Fours',
  'All the Colors of the Dark',
  'All the Sinners Bleed',
  'American Gods',
  'Annie Bot',
  'Anxious People',
  'Apples Never Fall',
  'Babel',
  'Beautiful World Where Are You',
  'Beautyland',
  'Beloved',
  'Bewilderment',
  'Birnam Wood',
  'Black Cake',
  'Black Sun',
  'Blackouts',
  'Book Currently Reading',
  'Book Marked DNF',
  'Book On TBR',
  'Book With Half Star',
  'Book With Long Review',
  'Book With No ISBN',
  'Book With No ISBN At All',
  'Book With No Rating',
  'Bookshops & Bonedust',
  'Booth',
  'Boy Parts',
  'Brave New World',
  'Brood',
  'Cahokia Jazz',
  'Chain-Gang All-Stars',
  'Children of Time',
  'Circe',
  'Clark and Division',
  'Cloud Cuckoo Land',
  'Companion Piece',
  'Counterfeit',
  'Creation Lake',
  'Crime and Punishment',
  'Crook Manifesto',
  'Crossroads',
  'Crying in H Mart',
  'Dead Collections',
  'Demon Copperhead',
  'Detransition Baby',
  'Detransition, Baby',
  'Divine Rivals',
  'Dune',
  'Elder Race',
  'Elektra',
  'Emily Wilde''s Map of the Otherlands',
  'Empire of Pain',
  'Fahrenheit 451',
  'Fairy Tale',
  'Fangirl',
  'Fellowship Point',
  'Fevered Star',
  'Five Star Book',
  'Foundation',
  'Fourth Wing',
  'Frankenstein',
  'Freakonomics',
  'Gone Girl',
  'Good Omens',
  'Great Circle',
  'Hamnet',
  'Happy Place',
  'Harlem Shuffle',
  'Harrow the Ninth',
  'Heart of Darkness',
  'Hell Bent',
  'Hell Followed With Us',
  'Hello Beautiful',
  'Holly',
  'Homeland Elegies',
  'Horse',
  'House of Flame and Shadow',
  'How Beautiful We Were',
  'How High We Go in the Dark',
  'How the Word Is Passed',
  'I Have Some Questions for You',
  'I''m Glad My Mom Died',
  'I''m a Fan',
  'In the Lives of Puppets',
  'Interior Chinatown',
  'Intermezzo',
  'Intimacies',
  'Iron Flame',
  'It',
  'James',
  'Jane Eyre',
  'Karima Has No Room to Breathe',
  'Klara and the Sun',
  'Lake of Darkness',
  'Lapvona',
  'Leave the World Behind',
  'Legends & Lattes',
  'Lessons in Chemistry',
  'Liberation Day',
  'Light From Uncommon Stars',
  'Lone Women',
  'Lucy by the Sea',
  'Maame',
  'Malibu Rising',
  'Matrix',
  'Memorial Drive',
  'Mexican Gothic',
  'Mislaid in Parts Half-Known',
  'Moon Witch Spider King',
  'Moonbound',
  'My Brilliant Friend',
  'My Year of Rest and Relaxation',
  'Nettle & Bone',
  'Neuromancer',
  'Nightcrawling',
  'No One Is Talking About This',
  'Nona the Ninth',
  'Noor',
  'Normal People',
  'North Woods',
  'Olga Dies Dreaming',
  'One Hundred Years of Solitude',
  'One Last Stop',
  'Orbital',
  'Our Share of Night',
  'Our Wives Under the Sea',
  'Peaces',
  'Pineapple Street',
  'Piranesi',
  'Plutoshine',
  'Portrait of an Unknown Woman',
  'Poverty, by America',
  'Pride and Prejudice',
  'Project Hail Mary',
  'Prophet Song',
  'Quietly Hostile',
  'Rakesfall',
  'Razorblade Tears',
  'Remarkably Bright Creatures',
  'Run Rose Run',
  'Run Towards the Danger',
  'S.',
  'Sahara Special',
  'Saint Death''s Daughter',
  'Sammy Went to Oxford and All He Got Was a Bloody Book',
  'Sapiens',
  'Sea of Tranquility',
  'Service Model',
  'Sharks in the Time of Saviours',
  'She Is a Haunting',
  'She Who Became the Sun',
  'Shuggie Bain',
  'Slaughterhouse-Five',
  'Small Mercies',
  'Small Things Like These',
  'Some Desperate Glory',
  'Someone You Can Build a Nest In',
  'Sorrow and Bliss',
  'Sorrowland',
  'South to America',
  'Starter Villain',
  'Stay True',
  'Stella Maris',
  'Stolen by the Borrowed Night',
  'System Collapse',
  'The Adventures of Amina al-Sirafi',
  'The Alchemist',
  'The Anxious Generation',
  'The Archive Undying',
  'The Atlas Six',
  'The Bee Sting',
  'The Bees',
  'The Bell Jar',
  'The Blade Itself',
  'The Bone Shard Daughter',
  'The Book of Doors',
  'The Bound Worlds',
  'The Bruising of Qilwa',
  'The Bullet Swallower',
  'The Candy House',
  'The Cartographers',
  'The City in Glass',
  'The Covenant of Water',
  'The Curator',
  'The Daughter of Doctor Moreau',
  'The Deep',
  'The Deep Sky',
  'The Deluge',
  'The Doors of Eden',
  'The Echo Wife',
  'The Employees',
  'The Empress of Salt and Fortune',
  'The Every',
  'The Familiar',
  'The Fifth Season',
  'The Fox Wife',
  'The Foxglove King',
  'The Fraud',
  'The Frugal Wizard''s Handbook for Surviving Medieval England',
  'The Furrows',
  'The Galaxy, and the Ground Within',
  'The Ghost Orchid',
  'The God of the Woods',
  'The Goldfinch',
  'The Great Gatsby',
  'The Great Reclamation',
  'The Grief of Stones',
  'The Handmaid''s Tale',
  'The Heaven & Earth Grocery Store',
  'The Hobbit',
  'The House in the Cerulean Sea',
  'The House of Rust',
  'The Invisible Life of Addie LaRue',
  'The Island of Missing Trees',
  'The It Girl',
  'The Jasmine Throne',
  'The Kaiju Preservation Society',
  'The Last Tale of the Flower Bride',
  'The Last Thing He Told Me',
  'The Light Pirate',
  'The Lincoln Highway',
  'The Long Halloween',
  'The Lord of the Rings',
  'The Lost Apothecary',
  'The Luminous Dead',
  'The Maid',
  'The Maidens',
  'The Making of Another Major Motion Picture Masterpiece',
  'The Marriage Portrait',
  'The Memory Police',
  'The Mercy of Gods',
  'The Midnight Library',
  'The Mimicking of Known Successes',
  'The Ministry of Time',
  'The Mountain in the Sea',
  'The Name of the Wind',
  'The Netanyahus',
  'The Night Watchman',
  'The Oleander Sword',
  'The Once and Future Witches',
  'The Paradox Hotel',
  'The Passenger',
  'The Personal Librarian',
  'The Phoenix Keeper',
  'The Phoenix King',
  'The Pomegranate Gate',
  'The Practice House',
  'The Prophets',
  'The Rabbit Hutch',
  'The Removed',
  'The Road',
  'The Saint of Bright Doors',
  'The School for Good Mothers',
  'The Secret History',
  'The Sentence',
  'The Silent Patient',
  'The Silverblood Promise',
  'The Siren of Sussex',
  'The Spear Cuts Through Water',
  'The Stand',
  'The Starless Crown',
  'The Surviving Sky',
  'The Tainted Cup',
  'The Talisman',
  'The Terraformers',
  'The Three-Body Problem',
  'The Trees',
  'The Tusks of Extinction',
  'The Unmaking of June Farrow',
  'The Vanished Birds',
  'The Vanishing Half',
  'The Wager',
  'The Warm Hands of Ghosts',
  'The Warm Months',
  'The Water Outlaws',
  'The Way of Kings',
  'The Wings Upon Her Back',
  'The Women',
  'The World We Make',
  'Thornhedge',
  'To Kill a Mockingbird',
  'Tom Lake',
  'Tomorrow and Tomorrow and Tomorrow',
  'Tomorrow, and Tomorrow, and Tomorrow',
  'Toward Eternity',
  'Transcendent Kingdom',
  'Translation State',
  'Tress of the Emerald Sea',
  'Trust',
  'Under the Whispering Door',
  'Unfinished Book',
  'Unicode Title: Café Stories',
  'Upgrade',
  'Venomous Lumpsucker',
  'Vera Wong''s Unsolicited Advice for Murderers',
  'Vladimir',
  'Wandering Stars',
  'Want to Read',
  'When the Moon Hatched',
  'Whereabouts',
  'While Justice Sleeps',
  'Who Is Maud Dixon?',
  'Win Every Argument',
  'Witch King',
  'Yellowface',
  'You Like It Darker',
  'Young Mungo'
);

COMMIT;
