name: Deploy to DigitalOcean
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get commit hash
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  # Tag with 'latest'
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/bibliotype:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/bibliotype:${{ steps.vars.outputs.sha_short }}

            - name: Deploy to DigitalOcean VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.DO_SSH_HOST }}
                  username: ${{ secrets.DO_SSH_USERNAME }}
                  key: ${{ secrets.DO_SSH_KEY }}
                  script: |
                      export IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
                      export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

                      export $(cat /home/bibliotype/app/.env | xargs)

                      cd /home/bibliotype/app

                      docker pull $DOCKERHUB_USERNAME/bibliotype:$IMAGE_TAG

                      docker compose -f docker-compose.prod.yml up -d --force-recreate

                      echo "Pruning old Docker images..."
                      docker image prune -f
