name: Deploy to DigitalOcean

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/bibliotype:latest

            - name: Deploy to DigitalOcean VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.DO_SSH_HOST }}
                  username: ${{ secrets.DO_SSH_USERNAME }}
                  key: ${{ secrets.DO_SSH_KEY }}
                  script: |
                      cd /home/bibliotype/app
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bibliotype:latest
                      docker-compose -f docker-compose.prod.yml up -d
                      docker image prune -f
